# Generated by Django 5.2.5 on 2026-03-31 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rack_unit_allocations', models.PositiveSmallIntegerField(null=True)),
                ('starting_position', models.PositiveSmallIntegerField(null=True)),
                ('name', models.CharField(db_index=True, max_length=50, null=True)),
                ('type', models.CharField(choices=[('server', 'Server'), ('switch', 'Switch'), ('appliance', 'Appliance')], max_length=20)),
                ('model', models.CharField(max_length=50, null=True)),
                ('serial_number', models.CharField(db_index=True, max_length=30, null=True, unique=True)),
                ('ipv4_address', models.CharField(max_length=15, null=True)),
                ('weight', models.PositiveIntegerField(blank=True, null=True)),
                ('power', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('decommissioned', 'Decommissioned')], db_index=True, default='active', max_length=30)),
                ('interface_count', models.IntegerField(blank=True, null=True)),
                ('description', models.CharField(max_length=300, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ApplianceChassis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name', models.CharField(max_length=100)),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('slot_position', models.PositiveIntegerField()),
                ('is_occupied', models.BooleanField(default=False)),
                ('is_chassis', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Appliance Chasis Module',
                'verbose_name_plural': 'Appliance Chasis Modules',
                'db_table': 'assets_appliance_chassis',
            },
        ),
        migrations.CreateModel(
            name='FanUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fan_count', models.IntegerField(default=1)),
                ('fan_speed', models.IntegerField(default=0, null=True)),
                ('is_internal', models.BooleanField(default=True, null=True)),
                ('wattage_max_output', models.FloatField(default=0.0, null=True)),
                ('wattage_average', models.FloatField(default=0.0, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'assets_fan_unit',
            },
        ),
        migrations.CreateModel(
            name='Interface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('interface_number', models.PositiveSmallIntegerField()),
                ('to_location', models.CharField(blank=True, max_length=100, null=True)),
                ('cable_type', models.CharField(blank=True, max_length=100, null=True)),
                ('port_type', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'ordering': ['interface_number'],
            },
        ),
        migrations.CreateModel(
            name='MemoryUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ram_capacity', models.PositiveIntegerField()),
                ('quantity', models.PositiveIntegerField(null=True)),
            ],
            options={
                'db_table': 'assets_memory_unit',
            },
        ),
        migrations.CreateModel(
            name='PowerSupplyUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('heat_dissipation', models.FloatField(default=0)),
                ('max_output', models.PositiveSmallIntegerField()),
                ('average_output', models.FloatField(blank=True, null=True)),
                ('wattage_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('power_type', models.CharField(default='', max_length=100)),
                ('connector_type', models.CharField(default='', max_length=100)),
                ('description', models.CharField(max_length=300, null=True)),
            ],
            options={
                'db_table': 'assets_power_supply_unit',
            },
        ),
        migrations.CreateModel(
            name='ProcessorUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='StorageUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_type', models.CharField(choices=[('HDD', 'HDD'), ('SSD', 'SSD')], max_length=10)),
                ('storage_capacity', models.PositiveIntegerField()),
                ('storage_count', models.PositiveIntegerField(default=1)),
                ('capacity_unit', models.CharField(choices=[('TB', 'TB'), ('GB', 'GB')], default='GB', max_length=10)),
            ],
            options={
                'db_table': 'assets_storage_unit',
            },
        ),
        migrations.CreateModel(
            name='TransceiverUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Transceiver Unit',
                'verbose_name_plural': 'Transceiver Units',
                'db_table': 'assets_transceiver_unit',
            },
        ),
        migrations.CreateModel(
            name='Appliance',
            fields=[
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='assets.device')),
                ('is_chassis', models.BooleanField(default=False)),
                ('has_components_units', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Appliance',
                'verbose_name_plural': 'Appliances',
                'db_table': 'assets_appliance',
            },
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='assets.device')),
                ('classification', models.CharField(max_length=100)),
                ('module_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'assets_server',
            },
        ),
        migrations.CreateModel(
            name='Switch',
            fields=[
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='switch', serialize=False, to='assets.device')),
            ],
            options={
                'db_table': 'assets_switch',
            },
        ),
    ]
