# Generated by Django 5.2.5 on 2026-03-31 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        ('enums', '0001_initial'),
        ('infrastructure', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='rack',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='infrastructure.rack'),
        ),
        migrations.AddField(
            model_name='appliancechassis',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chasis_modules', to='assets.device'),
        ),
        migrations.AddField(
            model_name='fanunit',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fan_units', to='assets.device'),
        ),
        migrations.AddField(
            model_name='interface',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interfaces', to='assets.device'),
        ),
        migrations.AddField(
            model_name='memoryunit',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memory_units', to='assets.device'),
        ),
        migrations.AddField(
            model_name='powersupplyunit',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='power_supply_units', to='assets.device'),
        ),
        migrations.AddField(
            model_name='fanunit',
            name='psu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fan_units', to='assets.powersupplyunit'),
        ),
        migrations.AddField(
            model_name='processorunit',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processor_units', to='assets.device'),
        ),
        migrations.AddField(
            model_name='processorunit',
            name='processor_codename',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='units', to='enums.processorcodename'),
        ),
        migrations.AddField(
            model_name='processorunit',
            name='processor_model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='units', to='enums.processormodel'),
        ),
        migrations.AddField(
            model_name='processorunit',
            name='processor_tier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='units', to='enums.processortier'),
        ),
        migrations.AddField(
            model_name='storageunit',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_units', to='assets.device'),
        ),
        migrations.AddField(
            model_name='storageunit',
            name='form_factor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='storage_units', to='enums.storageformfactor'),
        ),
        migrations.AddField(
            model_name='storageunit',
            name='storage_interface',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='storage_units', to='enums.storageinterface'),
        ),
        migrations.AddField(
            model_name='transceiverunit',
            name='interface',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transceiver_units', to='assets.interface'),
        ),
        migrations.AddField(
            model_name='transceiverunit',
            name='transceiver_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transceiver_units', to='enums.transceivertype'),
        ),
        migrations.AddField(
            model_name='appliance',
            name='appliance_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='enums.appliancetype'),
        ),
        migrations.AlterUniqueTogether(
            name='appliancechassis',
            unique_together={('device', 'slot_position')},
        ),
        migrations.AddConstraint(
            model_name='interface',
            constraint=models.UniqueConstraint(fields=('device', 'interface_number'), name='uniq_device_interface_number'),
        ),
    ]
