# Generated by Django 5.2.5 on 2026-03-31 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApplianceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_chassis', models.BooleanField(default=False)),
                ('has_compute_units', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'enums_appliance_type',
            },
        ),
        migrations.CreateModel(
            name='NetworkArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
            ],
            options={
                'db_table': 'enums_network_area',
            },
        ),
        migrations.CreateModel(
            name='ProcessorBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
                'db_table': 'enums_processor_brands',
            },
        ),
        migrations.CreateModel(
            name='StorageFormFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'enums_storage_formfactor',
            },
        ),
        migrations.CreateModel(
            name='StorageInterface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'enums_storage_interface',
            },
        ),
        migrations.CreateModel(
            name='TransceiverType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Transceiver Type',
                'verbose_name_plural': 'Transceiver Types',
                'db_table': 'enums_transceiver_type',
            },
        ),
        migrations.CreateModel(
            name='NetworkAreaOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='enums.networkarea')),
            ],
            options={
                'db_table': 'enums_network_area_order',
            },
        ),
        migrations.CreateModel(
            name='ProcessorCodename',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codenames', to='enums.processorbrand')),
            ],
            options={
                'verbose_name': 'Processor Codename',
                'verbose_name_plural': 'Processor Codenames',
                'db_table': 'enums_processor_codenames',
                'unique_together': {('name', 'brand')},
            },
        ),
        migrations.CreateModel(
            name='ProcessorTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiers', to='enums.processorbrand')),
            ],
            options={
                'verbose_name': 'Processor Tier',
                'verbose_name_plural': 'Processor Tiers',
                'db_table': 'enums_processor_tiers',
                'unique_together': {('name', 'brand')},
            },
        ),
        migrations.CreateModel(
            name='ProcessorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('codename', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='enums.processorcodename')),
                ('tier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='enums.processortier')),
            ],
            options={
                'unique_together': {('name', 'codename', 'tier')},
            },
        ),
    ]
