# Generated by Django 5.2.5 on 2026-03-31 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=50, null=True)),
                ('username', models.CharField(blank=True, max_length=150, null=True)),
                ('department', models.CharField(blank=True, max_length=150, null=True)),
                ('method', models.CharField(max_length=10)),
                ('path', models.CharField(max_length=255)),
                ('status_code', models.IntegerField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('browser', models.CharField(blank=True, max_length=200, null=True)),
                ('os_device', models.CharField(blank=True, max_length=200, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'logs_access_log',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user_id'], name='idx_accesslog_user'), models.Index(fields=['status_code', 'timestamp'], name='idx_accesslog_status_ts')],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=50, null=True)),
                ('username', models.CharField(blank=True, max_length=150, null=True)),
                ('department', models.CharField(blank=True, max_length=150, null=True)),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete')], max_length=20)),
                ('target', models.CharField(max_length=200)),
                ('target_id', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(default='success', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('browser', models.CharField(blank=True, max_length=200, null=True)),
                ('os_device', models.CharField(blank=True, max_length=200, null=True)),
                ('detail', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'logs_audit_log',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user_id'], name='idx_auditlog_user'), models.Index(fields=['action', 'timestamp'], name='idx_auditlog_action_ts')],
            },
        ),
    ]
