from .devices import DeviceSerializer, DeviceDetailSerializer,RackPositionSummarySerializer
from .devices import SwitchSummarySerializer, SwitchWriteSerializer
from .devices import ServerSummarySerializer, ServerDetailSerializer, ServerWriteSerializer
from .devices import ApplianceSummarySerializer, ApplianceDetailSerializer, ApplianceWriteSerializer
from .devices import ApplianceChassisDetailSerializer, ApplianceChassisSummarySerializer

from .components import InterfaceDetailSerializer, InterfaceSummarySerializer
from .components import PowerSupplyUnitSerializer, ShowAllPowerSupplyUnitSerializer
from .components import InterfaceSummarySerializer, InterfaceDetailSerializer
from .components import FanUnitSerializer, ShowAllFanUnitSerializer


