# Generated by Django 5.2.5 on 2026-03-31 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        ('enums', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailabilityZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=25, unique=True)),
                ('location', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'infrastructure_availability_zone',
            },
        ),
        migrations.CreateModel(
            name='Pod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PowerDeliveryUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.CharField(choices=[('left', 'Left'), ('right', 'Right')], max_length=10)),
                ('max_output', models.PositiveIntegerField(blank=True, default=0)),
                ('description', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'db_table': 'infrastructure_power_delivery_units',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=25, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=25, unique=True)),
                ('availability_zone', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='infrastructure.availabilityzone')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.PositiveSmallIntegerField()),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='infrastructure.building')),
            ],
        ),
        migrations.CreateModel(
            name='PowerDeliveryUnitOutlet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('outlet_number', models.PositiveSmallIntegerField()),
                ('to_location', models.CharField(max_length=100, null=True)),
                ('description', models.CharField(max_length=300, null=True)),
                ('power_delivery_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='power_delivery_unit', to='infrastructure.powerdeliveryunit')),
            ],
            options={
                'db_table': 'infrastructure_power_delivery_unit_outlet',
            },
        ),
        migrations.CreateModel(
            name='Rack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('environment', models.CharField(choices=[('TEST', 'Test Lab'), ('PROD', 'Production')], max_length=10, null=True)),
                ('number', models.CharField(max_length=30)),
                ('ru_count', models.PositiveSmallIntegerField(default=42)),
                ('weight', models.PositiveSmallIntegerField()),
                ('is_occupied', models.BooleanField(blank=True, default=False)),
                ('network_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='enums.networkarea')),
                ('network_area_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='enums.networkareaorder')),
                ('pod', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='infrastructure.pod')),
            ],
        ),
        migrations.AddField(
            model_name='powerdeliveryunit',
            name='rack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='power_delivery_units', to='infrastructure.rack'),
        ),
        migrations.CreateModel(
            name='RackPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position_number', models.PositiveSmallIntegerField()),
                ('is_occupied', models.BooleanField(blank=True, default=False)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rack_positions', to='assets.device')),
                ('rack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rack_positions', to='infrastructure.rack')),
            ],
            options={
                'db_table': 'infrastructure_rack_position',
                'ordering': ['-position_number'],
            },
        ),
        migrations.AddField(
            model_name='availabilityzone',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='infrastructure.region'),
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=30)),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='infrastructure.floor')),
            ],
        ),
        migrations.AddField(
            model_name='pod',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='infrastructure.room'),
        ),
        migrations.AddConstraint(
            model_name='floor',
            constraint=models.UniqueConstraint(fields=('number', 'building'), name='unique_floor_per_building'),
        ),
        migrations.AddConstraint(
            model_name='powerdeliveryunitoutlet',
            constraint=models.UniqueConstraint(fields=('outlet_number', 'power_delivery_unit'), name='unique_outlet_number_per_pdu'),
        ),
        migrations.AddConstraint(
            model_name='rack',
            constraint=models.UniqueConstraint(fields=('number', 'pod'), name='unique_rack_per_pod'),
        ),
        migrations.AddConstraint(
            model_name='powerdeliveryunit',
            constraint=models.UniqueConstraint(fields=('position', 'rack'), name='unique_pdu_position_per_rack'),
        ),
        migrations.AddConstraint(
            model_name='rackposition',
            constraint=models.UniqueConstraint(fields=('position_number', 'rack'), name='unique_rack_position'),
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.UniqueConstraint(fields=('number', 'floor'), name='unique_room_per_floor'),
        ),
        migrations.AddConstraint(
            model_name='pod',
            constraint=models.UniqueConstraint(fields=('name', 'room'), name='unique_pod_per_room'),
        ),
    ]
