# Generated by Django 6.0.1 on 2026-03-25 03:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, help_text='Stable department identifier (DO NOT CHANGE)', max_length=64, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'iam_department',
            },
        ),
    ]
