class RoleCodes:
    PLATFORM_ADMIN = "PLATFORM_ADMIN"
    # IAM_ADMIN = "IAM_ADMIN"

    INVENTORY_VIEWER = "INVENTORY_VIEWER"
    INVENTORY_ADMIN = "INVENTORY_ADMIN"

    PLECO_ADMIN = "PLECO_ADMIN"
    PLECO_VIEWER = "PLECO_VIEWER"
