"""
Django settings for playground project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import environ
import os
import sys

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Add the apps directory to Python path
sys.path.insert(0, os.path.join(BASE_DIR, 'inventory'))

# Initialize ENV management
env = environ.Env(
  # set casting, default value
  DEBUG=(bool, False)
)

# Take environment variables from .env file
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DEBUG')

ALLOWED_HOSTS = env.list('ALLOWED_HOSTS')

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Apps
    'infrastructure',
    'assets',
    'enums',
    'accounts',
    'seeder',

    # Django Rest Framework
    'rest_framework',
    'django_filters',
    'rest_framework_simplejwt',

    # CORS headers
    'corsheaders',
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'playground.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'playground.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Redis Settings
REDIS_HOST = env("REDIS_HOST")
REDIS_PORT = env("REDIS_PORT")
REDIS_DB = env("REDIS_DB")
REDIS_PASSWORD = env("REDIS_PASSWORD")

REDIS_URL = f"redis://{':' + REDIS_PASSWORD + '@' if REDIS_PASSWORD else ''}{REDIS_HOST}:{REDIS_PORT}/{REDIS_DB}"

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': env("DATABASE_NAME"),
        'USER': env("DATABASE_USER"),
        'PASSWORD': env("DATABASE_PASSWORD"),
        'HOST': env("DATABASE_HOST"),
        'PORT': env("DATABASE_PORT"),
    }
}



CACHES = {
  'default': {
    'BACKEND': 'django_redis.cache.RedisCache',
    'LOCATION': REDIS_URL,
    'OPTIONS': {
        'CLIENT_CLASS': 'django_redis.client.DefaultClient',
        'SERIALIZER': 'django_redis.serializers.json.JSONSerializer',  # <<< Use JSON
    },
    "KEY_PREFIX": "",  # remove :1:
    "VERSION": 1,      # keep consistent
  }
}



# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

# TIMEZONE
USE_TZ = True
TIME_ZONE = 'Asia/Manila'
USE_I18N = True





# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    # PERMISSION   
    'DEFAULT_PERMISSION_CLASSES': (
    'rest_framework.permissions.IsAuthenticated',
    'accounts.permissions.IsNotLocked',
    # 'rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly',  # for browsable API login
    ),

    # PAGINATION
    # 'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    # 'PAGE_SIZE': 10,
    'DEFAULT_PAGINATION_CLASS': 'utils.pagination.CustomPagination',
    'PAGE_SIZE': 10,


    # FILTERS
    'DEFAULT_FILTER_BACKENDS': [
      'django_filters.rest_framework.DjangoFilterBackend',
      'rest_framework.filters.SearchFilter',
    ],

    # AUTHENTICATION
    'DEFAULT_AUTHENTICATION_CLASSES': [
        # "rest_framework.authentication.SessionAuthentication",
        # "auth.authenticate.JWKSJWTAuthentication",
        'auth.authenticate.IAMCookieJWTAuthentication'
    ],

    # CUSTOM EXCEPTION
    'EXCEPTION_HANDLER': 'utils.exceptions.custom_exception_handler'
}


from datetime import timedelta

# SIMPLE_JWT = {
#     'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
#     'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
#     'ROTATE_REFRESH_TOKENS': True,
#     'BLACKLIST_AFTER_ROTATION': True,
#     'AUTH_HEADER_TYPES': ('Bearer',),
# }

# --------------------------------------------------
# JWT / IAM configuration (from IAM)
# --------------------------------------------------

JWT_ISSUER = os.environ.get("JWT_ISSUER", "gaia-iam")
JWT_AUDIENCE = os.environ.get("JWT_AUDIENCE", "gaia-api")

JWT_PUBLIC_KEY = os.environ.get("JWT_PUBLIC_KEY")
if not JWT_PUBLIC_KEY:
    raise RuntimeError("JWT_PUBLIC_KEY is not set")




# Abstract User Model
AUTH_USER_MODEL = "accounts.User"

# CORS
CORS_ALLOWED_ORIGINS = env.list('CORS_ALLOWED_ORIGINS')
CORS_ALLOW_CREDENTIALS = True


# CSRF
CSRF_TRUSTED_ORIGINS = env.list('CSRF_TRUSTED_ORIGINS')
CSRF_COOKIE_HTTPONLY = False
CSRF_COOKIE_SECURE = False
CSRF_COOKIE_SAMESITE = "Lax"

# SESSION COOKIE
SESSION_COOKIE_SECURE = False
SESSION_COOKIE_SAMESITE = "Lax"


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/
# python manage.py collecstatic
from pathlib import Path

# =========================
# STATIC FILES (CSS, JS)
# =========================

# URL prefix used by Django & Nginx to access static files
STATIC_URL = "/static/"

# Directory where `collectstatic` will copy ALL static files
# This directory should be served by Nginx in production
STATIC_ROOT = BASE_DIR / "staticfiles"

# Extra directories Django will SEARCH for static files
# (used during development and by collectstatic)
STATICFILES_DIRS = [
    BASE_DIR / "inventory" / "static",
]

# NOTE:
# - STATICFILES_DIRS = source locations
# - STATIC_ROOT = destination (DO NOT overlap them)


# =========================
# MEDIA FILES (User uploads)
# =========================

# URL prefix for user-uploaded files
MEDIA_URL = "/media/"

# Directory where uploaded files are stored
# Must be writable by the Django process
MEDIA_ROOT = BASE_DIR / "media"


# APPEND_SLASH = False



#new

IAM_JWKS_URL = "http://127.0.0.1:8000/.well-known/jwks.json"
IAM_JWKS_CACHE_TTL = 300  # seconds

JWT_ISSUER = "gaia-iam"
JWT_AUDIENCE = "gaia-api"

IAM_BASE_URL = "http://localhost:8000"
IAM_COOKIE_NAME = "access"
