"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import environ
import os
import sys

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# Initialize ENV management
env = environ.Env(
  # set casting, default value
  DEBUG=(bool, False)
)


# Take environment variables from .env file
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))


# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')

# # SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True




# --------------------------------------------------
# Applications
# --------------------------------------------------

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third Party
    "rest_framework",
    "rest_framework_simplejwt",
    "rest_framework_simplejwt.token_blacklist",

    # Apps
    "seeder",
    "apps.identity",
    "apps.department",
    "apps.access",
    "apps.authn",
    "apps.authz"     # even without models
    # "apps.audit",      # if you keep audit models
    # "apps.services",   # service registry (if it has models)

]

# --------------------------------------------------
# Middleware
# --------------------------------------------------

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# --------------------------------------------------
# URLs / WSGI
# --------------------------------------------------

ROOT_URLCONF = 'config.urls'

WSGI_APPLICATION = 'config.wsgi.application'

# --------------------------------------------------
# Templates
# --------------------------------------------------

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# --------------------------------------------------
# Database (DEFAULT STRUCTURE)
# --------------------------------------------------

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': env("DATABASE_NAME"),
        'USER': env("DATABASE_USER"),
        'PASSWORD': env("DATABASE_PASSWORD"),
        'HOST': env("DATABASE_HOST"),
        'PORT': env("DATABASE_PORT"),
    }
}


# --------------------------------------------------
# Password validation
# --------------------------------------------------

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# --------------------------------------------------
# Internationalization
# --------------------------------------------------

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Asia/Manila'
USE_I18N = True
USE_TZ = True

# --------------------------------------------------
# DJANGO DRF
# --------------------------------------------------
REST_FRAMEWORK = {
    # PERMISSION   
    'DEFAULT_PERMISSION_CLASSES': (
    'rest_framework.permissions.IsAuthenticated',
    # 'iam.permissions.IsNotLocked',
    # 'rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly',  # for browsable API login
    ),

    # PAGINATION
    # 'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    # 'PAGE_SIZE': 10,
    # 'DEFAULT_PAGINATION_CLASS': 'utils.pagination.CustomPagination',
    # 'PAGE_SIZE': 10,


    # FILTERS
    'DEFAULT_FILTER_BACKENDS': [
      'django_filters.rest_framework.DjangoFilterBackend',
      'rest_framework.filters.SearchFilter',
    ],

    # AUTHENTICATION
    'DEFAULT_AUTHENTICATION_CLASSES': (
        # 'iam.authentication.jwt.CustomAuthentication',
        # "rest_framework_simplejwt.authentication.JWTAuthentication",
        'apps.authn.authentication.HybridJWTAuthentication',

    ),

    # CUSTOM EXCEPTION
    # 'EXCEPTION_HANDLER': 'utils.exceptions.custom_exception_handler'
}

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# STATIC_URL = 'static/'
# URL prefix used by Django & Nginx to access static files
STATIC_URL = "/static/"
# Extra directories Django will SEARCH for static files
# (used during development and by collectstatic)
STATIC_ROOT = BASE_DIR / "staticfiles"
# NOTE:
# - STATICFILES_DIRS = source locations
# - STATIC_ROOT = destination (DO NOT overlap them)


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'



# =========================
# MEDIA FILES (User uploads)
# =========================

# URL prefix for user-uploaded files
MEDIA_URL = "/media/"

# Directory where uploaded files are stored
# Must be writable by the Django process
MEDIA_ROOT = BASE_DIR / "media"

# --------------------------------------------------
# JWT
# --------------------------------------------------
from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
}
# JWT settings
JWT_PRIVATE_KEY= (BASE_DIR / "keys" / "private.pem").read_text()
JWT_PUBLIC_KEY = (BASE_DIR / "keys" / "public.pem").read_text()

SIMPLE_JWT = {
    # 🔐 Crypto
    "ALGORITHM": "RS256",
    "SIGNING_KEY": JWT_PRIVATE_KEY,
    "VERIFYING_KEY": JWT_PUBLIC_KEY,

    # 🏷 Issuer / Audience (microservice trust)
    "ISSUER": "gaia-iam",
    "AUDIENCE": "gaia-api",

    # ⏱ Lifetimes
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=15),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),

    # 🔁 Rotation & revocation
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,

    # 🧾 Header (still useful for non-browser clients)
    "AUTH_HEADER_TYPES": ("Bearer",),
}

# --------------------------------------------------
# Authentication 
# --------------------------------------------------
# Abstract User Model
AUTH_USER_MODEL = "identity.User"
AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
]
DEBUG = env.bool("DEBUG", default=False)

# SESSION COOKIE
SESSION_COOKIE_SECURE = not DEBUG
SESSION_COOKIE_SAMESITE = "Lax"

# CSRF
CSRF_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SAMESITE = "Lax"
CSRF_COOKIE_HTTPONLY = False  # must be readable by JS

# CORS
CORS_ALLOWED_ORIGINS = env.list('CORS_ALLOWED_ORIGINS')
CORS_ALLOW_CREDENTIALS = True
