# Generated by Django 6.0.1 on 2026-03-27 06:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('auth.login', 'Auth Login'), ('auth.login_failed', 'Auth Login Failed'), ('auth.logout', 'Auth Logout'), ('auth.token_refresh', 'Auth Token Refresh'), ('user.create', 'User Create'), ('user.update', 'User Update'), ('user.delete', 'User Delete'), ('user.reset_password', 'User Reset Password'), ('user.change_password', 'User Change Password'), ('dept.create', 'Dept Create'), ('dept.update', 'Dept Update'), ('dept.delete', 'Dept Delete')], db_index=True, max_length=50)),
                ('target_id', models.UUIDField(blank=True, null=True)),
                ('target_type', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failure', 'Failure')], default='success', max_length=10)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'iam_audit_log',
                'ordering': ['-timestamp'],
            },
        ),
    ]
