# Generated by Django 6.0.1 on 2026-03-31 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('auth.login', 'Auth Login'), ('auth.login_failed', 'Auth Login Failed'), ('auth.logout', 'Auth Logout'), ('auth.token_refresh', 'Auth Token Refresh'), ('user.create', 'User Create'), ('user.update', 'User Update'), ('user.delete', 'User Delete'), ('user.reset_password', 'User Reset Password'), ('user.change_password', 'User Change Password'), ('department.create', 'Dept Create'), ('department.update', 'Dept Update'), ('department.delete', 'Dept Delete')], db_index=True, max_length=50),
        ),
    ]
