# Generated by Django 6.0.1 on 2026-02-14 08:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentAllowedRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'iam_department_allowed_role',
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=150, unique=True)),
                ('system', models.CharField(max_length=50)),
                ('resource', models.CharField(max_length=50)),
                ('action', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'iam_permission',
            },
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, help_text='Stable policy identifier (DO NOT CHANGE)', max_length=100, unique=True)),
                ('label', models.CharField(help_text='Human-readable label (e.g. AZ – Read & Update)', max_length=100)),
                ('system', models.CharField(help_text='Owning service (inventory, iam, monitoring)', max_length=50)),
                ('resource', models.CharField(help_text='Resource name (az, device, user, etc.)', max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'iam_policy',
            },
        ),
        migrations.CreateModel(
            name='PolicyPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'iam_policy_permission',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, help_text='Stable system identifier (DO NOT CHANGE)', max_length=64, unique=True)),
                ('name', models.CharField(help_text='Display name', max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'iam_role',
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'iam_role_permission',
            },
        ),
        migrations.CreateModel(
            name='RolePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'iam_role_policy',
            },
        ),
        migrations.CreateModel(
            name='UserPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'iam_user_policy',
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'iam_user_role',
            },
        ),
    ]
