# Generated by Django 6.0.1 on 2026-03-23 06:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=150, unique=True)),
                ('system', models.CharField(max_length=50)),
                ('resource', models.CharField(max_length=50)),
                ('action', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'iam_permission',
            },
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, help_text='Stable policy identifier (DO NOT CHANGE)', max_length=100, unique=True)),
                ('name', models.CharField(help_text='Human-readable name (e.g. AZ – Read & Update)', max_length=100)),
                ('system', models.CharField(help_text='Owning service (inventory, iam, monitoring)', max_length=50)),
                ('resource', models.CharField(help_text='Resource name (az, device, user, etc.)', max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'iam_policy',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, help_text='Stable system identifier (DO NOT CHANGE)', max_length=64, unique=True)),
                ('name', models.CharField(help_text='Display name', max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'iam_role',
            },
        ),
        migrations.CreateModel(
            name='UserPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('role', 'Role'), ('direct', 'Direct')], default='role', max_length=10)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'iam_user_permission',
            },
        ),
        migrations.CreateModel(
            name='UserPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('role', 'Role'), ('extra', 'Extra')], default='role', max_length=10)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'iam_user_policy',
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'iam_user_role',
            },
        ),
        migrations.CreateModel(
            name='DepartmentAllowedSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system', models.CharField(max_length=50)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowed_system_entries', to='department.department')),
            ],
            options={
                'db_table': 'iam_department_allowed_system',
            },
        ),
        migrations.CreateModel(
            name='PolicyPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_policies', to='access.permission')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policy_permissions', to='access.policy')),
            ],
            options={
                'db_table': 'iam_policy_permission',
            },
        ),
        migrations.CreateModel(
            name='RolePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policy_roles', to='access.policy')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_policies', to='access.role')),
            ],
            options={
                'db_table': 'iam_role_policy',
            },
        ),
    ]
