# Generated by Django 6.0.1 on 2026-02-01 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0001_initial'),
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentAllowedRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowed_roles', to='department.department')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowed_departments', to='access.role')),
            ],
            options={
                'db_table': 'iam_department_allowed_role',
                'unique_together': {('department', 'role')},
            },
        ),
    ]
