# Generated by Django 6.0.1 on 2026-03-23 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserPolicy',
        ),
    ]
