# Generated by Django 6.0.1 on 2026-02-14 08:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('access', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userpolicy',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_policies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userpolicy',
            name='policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policy_users', to='access.policy'),
        ),
        migrations.AddField(
            model_name='userpolicy',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_policies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userrole',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_roles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userrole',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_users', to='access.role'),
        ),
        migrations.AddField(
            model_name='userrole',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='policypermission',
            unique_together={('policy', 'permission')},
        ),
        migrations.AddIndex(
            model_name='departmentallowedrole',
            index=models.Index(fields=['department'], name='iam_departm_departm_5309a2_idx'),
        ),
        migrations.AddIndex(
            model_name='departmentallowedrole',
            index=models.Index(fields=['role'], name='iam_departm_role_id_bebea2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='departmentallowedrole',
            unique_together={('department', 'role')},
        ),
        migrations.AlterUniqueTogether(
            name='rolepermission',
            unique_together={('role', 'permission')},
        ),
        migrations.AlterUniqueTogether(
            name='rolepolicy',
            unique_together={('role', 'policy')},
        ),
        migrations.AlterUniqueTogether(
            name='userpolicy',
            unique_together={('user', 'policy')},
        ),
        migrations.AlterUniqueTogether(
            name='userrole',
            unique_together={('user', 'role')},
        ),
    ]
