class RoleCodes:
    # PLATFORM_ADMIN = "PLATFORM_ADMIN"
    SUPER_ADMIN = "SUPER_ADMIN"
    GLOBAL_VIEWER = "GLOBAL_VIEWER"

    IAM_ADMIN = "IAM_ADMIN"

    INVENTORY_VIEWER = "INVENTORY_VIEWER"
    INVENTORY_ADMIN = "INVENTORY_ADMIN"

    PLECO_ADMIN = "PLECO_ADMIN"
    PLECO_VIEWER = "PLECO_VIEWER"
